name: CI/CD Pipeline

on:
  push:
    branches: 
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Dependencies
      - name: Install Dependencies
        run: npm install
      
      # UAT/Unit Testing
      - name: Run Tests
        run: npm run test
      
      # Build Dockerfile
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/solo-cicd .
      
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      # Push to Docker Hub (เฉพาะ main branch)
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/solo-cicd
      
      # Generate Release (เฉพาะ main branch)
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.sha }}
          release_name: Release ${{ github.sha }}